def format_report(title, evaluation):

    report = f"""
# Judgement Report

## Paper Title
{title}

## Executive Summary
This evaluation was generated by a multi-agent AI system analyzing research quality.

## Agent Analysis
{evaluation['analysis']}
"""

    return report
