def generate_report(results):

    report = f"""
# Research Paper Evaluation Report

## Executive Summary
This report summarizes the automated evaluation of the submitted research paper
using a multi-agent AI analysis system.

---

## Detailed Agent Evaluation

{results}

---

## Evaluation Categories

**Consistency Score**
Assessment of whether the research methodology supports the results.

**Grammar Rating**
Evaluation of academic writing quality and clarity.

**Novelty Index**
Assessment of whether the research contribution appears original.

**Fact Check Log**
List of verified and questionable claims identified in the methodology.

**Fabrication Probability**
Estimated risk of fabricated data or statistical anomalies.

---

Generated by: **Agentic Research Paper Evaluator**
"""

    return report
