def generate_report(results):

    report = f"""
# Research Paper Evaluation Report

## Executive Summary
This report summarizes the automated evaluation of the submitted research paper.

---

## Consistency Analysis
{results}

---

## Grammar & Language Review
Evaluates academic tone and writing quality.

---

## Novelty Assessment
Estimates whether the research contribution appears original.

---

## Fact Check Log
Lists verified and questionable scientific claims.

---

## Fabrication Risk
Estimated probability of fabricated results or anomalies.

---

Generated by: Agentic Research Paper Evaluator
"""

    return report
